name: NPM 包发布

on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 检出
        uses: actions/checkout@v3

      - name: 安装 Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org

      - name: 构建库
        run: |
          npm ci
          npm run build

      - name: 发布至 NPM
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cp package.json README.md ./dist
          cd ./dist
          npm version ${{github.ref_name}}
          npm publish
