name: 单元测试

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

env:
  HOST: cmq-usw.public.tencenttdmq.com
  SECRETID: ${{ secrets.SECRETID }}
  SECRETKEY: ${{ secrets.SECRETKEY }}
  REGION: usw
  API_REGION: na-siliconvalley

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
      - name: 检出
        uses: actions/checkout@v3

      - name: 安装 Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: 安装依赖
        run: npm install

      - name: 启动单元测试
        run: npm test

      - name: 推送覆盖率至 COVERAGE
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
